<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    integer         irn
    table           Flags
      text short      TitObjectRating
    end
    text short      AdmPublishWebNoPassword
    text short      TitObjectStatus
    text short      TitAccessionNo
    text short      TitPreviousAccessionNo
    date            TitAccessionDate
    text long       TitMainTitle
    text long       TitSeriesTitle
    text long       TitCollectionTitle
    table           AltTitles
      text long       TitAlternateTitles
    end
    table           Creator
      integer         irn
      text short      CreRole
      text long       CreCreatorAfterFollower
    end
    table           Culture
      text long       CreCreatorAttribution
      text long       CreCreationCultureOrPeople
      text long       CreCreationNationality2
    end
    text short      CreDateCreated
    date            CreEarliestDate
    date            CreLatestDate
    text short      CreDateDesigned
    date            CreEarliestDesignDate
    date            CreLatestDesignDate
    text short      CreCreationPeriod
    text long       CreCreationDynasty
    table           CreLoc
      text short      CreCountry
      text short      CreState
      text short      CreDistrict
      text short      CreCity
    end
    text short      TitObjectType
    table           ObjType
      text short      PhyMediaCategory
    end
    table           Medium
      text long       PhyMedium
    end
    table           Support
      text short      PhySupport
    end
    text long       PhyMediumAndSupport
    text short      PhyTechnique
    text short      PhyStyle
    table           MarkType
      text short      CreMarkType
    end
    text long       CrePrimaryInscriptions
    table           Printer
      integer         irn
    end
    table           Publisher
      integer         irn
    end
    text long       PhyConvertedDims
    table           Dims
      text short      PhyType
      float           PhyHeight
      float           PhyWidth
      float           PhyDepth
      float           PhyDiameter
      text short      PhyUnitLength
      float           PhyWeight
      text short      PhyUnitWeight
      text short      PhyDimensionNotes
    end
    text long       SumCreditLine
    table           Rights
      integer         irn
      text long       RigAcknowledgement
    end
    table           RightsURIs
      text short      AdmGUIDIsPreferred_tab
      text long       AdmGUIDType_tab
      text long       AdmGUIDValue_tab
    end
    text long       CreProvenance
    text short      PhyCollectionArea
    text short      LocMovementType
    table           CurLoc
      tuple           LocCurrentLocationRef
        integer         irn
        text short      LocLocationCode
        text short      LocLevel1
        text short      LocLevel2
        text short      LocLevel3
        text short      LocLevel4
        text short      LocLevel5
        text short      LocLevel6
        text short      LocLevel7
        text short      LocLevel8
      end
    end
    table           PermLoc
      tuple           LocPermanentLocationRef
        integer         irn
        text short      LocLocationCode
        text short      LocLevel1
        text short      LocLevel2
        text short      LocLevel3
        text short      LocLevel4
        text short      LocLevel5
        text short      LocLevel6
        text short      LocLevel7
        text short      LocLevel8
      end
    end
    table           Parent
      tuple           AssParentObjectRef
        integer         irn
      end
    end
    table           Related
      text short      AssRelationship
      integer         irn
    end
    table           GUIDs
      text short      AdmGUIDIsPreferred
      text short      AdmGUIDType
      text short      AdmGUIDValue
    end
    table           DeaccessionDetails
      text short      DeaDeaccessionMethod
      date            DeaDeaccessionDate
      text long       DeaDeaccessionNotes
      tuple           DeaReceivingPartyRef
        integer         irn
      end
      text long       DeaTransferNotes
    end
    date            AdmDateModified
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">46950</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionNo">05.19</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitAccessionDate">1905</atom>
    <atom name="TitMainTitle">United States Flag</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <table name="Culture">
      <tuple>
        <atom name="CreCreationNationality2">American</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated"></atom>
    <atom name="CreEarliestDate"></atom>
    <atom name="CreLatestDate"></atom>
    <atom name="CreDateDesigned"></atom>
    <atom name="CreEarliestDesignDate"></atom>
    <atom name="CreLatestDesignDate"></atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="CreLoc">
      <tuple>
        <atom name="CreCountry">United States</atom>
      </tuple>
    </table>
    <atom name="TitObjectType">Furnishings</atom>
    <table name="ObjType">
      <tuple>
        <atom name="PhyMediaCategory">banners</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">flags</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">bunting</atom>
    <atom name="PhyTechnique"></atom>
    <atom name="PhyStyle"></atom>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="PhyConvertedDims">No measurement details.</atom>
    <atom name="SumCreditLine">Gift of Mrs. Eli Lilly</atom>
    <table name="Rights">
      <tuple>
        <atom name="irn">1707</atom>
        <atom name="RigAcknowledgement">No Known Rights Holder</atom>
      </tuple>
    </table>
    <table name="RightsURIs">
      <tuple>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">908-Textile and Fashion Arts</atom>
    <atom name="LocMovementType">Inventory</atom>
    <table name="CurLoc">
      <tuple>
        <tuple name="LocCurrentLocationRef">
          <atom name="irn">14916</atom>
          <atom name="LocLocationCode">Location Not Verified</atom>
          <atom name="LocLevel1">IMA</atom>
          <atom name="LocLevel2">Location Not Verified</atom>
          <atom name="LocLevel3"></atom>
          <atom name="LocLevel4"></atom>
          <atom name="LocLevel5"></atom>
          <atom name="LocLevel6"></atom>
          <atom name="LocLevel7"></atom>
          <atom name="LocLevel8"></atom>
        </tuple>
      </tuple>
    </table>
    <table name="GUIDs">
      <tuple>
        <atom name="AdmGUIDIsPreferred">No</atom>
        <atom name="AdmGUIDType">Dagwood ID</atom>
        <atom name="AdmGUIDValue">34951</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2022-06-07</atom>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="irn">21137</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionNo">06.137</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitAccessionDate">1906-05-01</atom>
    <atom name="TitMainTitle">Hakone</atom>
    <atom name="TitSeriesTitle">The Fifty-three Stations of the T^okaid^o</atom>
    <atom name="TitCollectionTitle"></atom>
    <table name="AltTitles">
      <tuple>
        <atom name="TitAlternateTitles">subtitle:  The Lake</atom>
      </tuple>
    </table>
    <table name="Creator">
      <tuple>
        <atom name="irn">592</atom>
        <atom name="CreRole">Artist</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1833-1834</atom>
    <atom name="CreEarliestDate">1833</atom>
    <atom name="CreLatestDate">1834</atom>
    <atom name="CreDateDesigned"></atom>
    <atom name="CreEarliestDesignDate"></atom>
    <atom name="CreLatestDesignDate"></atom>
    <atom name="CreCreationPeriod">Edo</atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="CreLoc">
      <tuple>
        <atom name="CreCountry">Japan</atom>
        <atom name="CreCity">Edo</atom>
      </tuple>
    </table>
    <atom name="TitObjectType">Visual Works: Prints</atom>
    <table name="ObjType">
      <tuple>
        <atom name="PhyMediaCategory">prints</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">color woodcuts</atom>
      </tuple>
    </table>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">ink</atom>
      </tuple>
      <tuple>
        <atom name="PhyMedium">colored ink</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">paper</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">ink on paper, color woodblock print</atom>
    <atom name="PhyTechnique">woodcutting</atom>
    <atom name="PhyStyle"></atom>
    <table name="MarkType">
      <tuple>
        <atom name="CreMarkType">Signature</atom>
      </tuple>
      <tuple>
        <atom name="CreMarkType">Seal</atom>
      </tuple>
      <tuple>
        <atom name="CreMarkType">Inscriptions</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions">Signed by artist: Hiroshige ga
Publisher's mark: Hōeidō (Takenouchi Magohachi)
Seal with subtitle: Kosuizu
Inscribed: title and series title</atom>
    <table name="Publisher">
      <tuple>
        <atom name="irn">2515</atom>
      </tuple>
      <tuple>
        <atom name="irn">2514</atom>
      </tuple>
    </table>
    <atom name="PhyConvertedDims">9 x 13-15/16 in. (image, sheet trimmed to image on all sides)</atom>
    <table name="Dims">
      <tuple>
        <atom name="PhyType">Image Dimensions</atom>
        <atom name="PhyHeight">9.0000</atom>
        <atom name="PhyWidth">13.9375</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 22.7 x 35.4 cm. (image)</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">John Herron Fund</atom>
    <table name="Rights">
      <tuple>
        <atom name="irn">809</atom>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <table name="RightsURIs">
      <tuple>
      </tuple>
    </table>
    <atom name="CreProvenance">Purchased by the John Herron Art Institute, Indianapolis, Indiana, now the Indianapolis Museum of Art at Newfields, in 1906.</atom>
    <atom name="PhyCollectionArea">905.2-Asian Art (Japanese and Korean)</atom>
    <atom name="LocMovementType">Inventory</atom>
    <table name="CurLoc">
      <tuple>
        <tuple name="LocCurrentLocationRef">
          <atom name="irn">10315</atom>
          <atom name="LocLocationCode">F25.cg5.r6.lv4</atom>
          <atom name="LocLevel1">IMA</atom>
          <atom name="LocLevel2">Print Storage</atom>
          <atom name="LocLevel3">F25</atom>
          <atom name="LocLevel4">cg5</atom>
          <atom name="LocLevel5">r6</atom>
          <atom name="LocLevel6">lv4</atom>
          <atom name="LocLevel7"></atom>
          <atom name="LocLevel8"></atom>
        </tuple>
      </tuple>
    </table>
    <table name="PermLoc">
      <tuple>
        <tuple name="LocPermanentLocationRef">
          <atom name="irn">10315</atom>
          <atom name="LocLocationCode">F25.cg5.r6.lv4</atom>
          <atom name="LocLevel1">IMA</atom>
          <atom name="LocLevel2">Print Storage</atom>
          <atom name="LocLevel3">F25</atom>
          <atom name="LocLevel4">cg5</atom>
          <atom name="LocLevel5">r6</atom>
          <atom name="LocLevel6">lv4</atom>
          <atom name="LocLevel7"></atom>
          <atom name="LocLevel8"></atom>
        </tuple>
      </tuple>
    </table>
    <table name="GUIDs">
      <tuple>
        <atom name="AdmGUIDIsPreferred">No</atom>
        <atom name="AdmGUIDType">Dagwood ID</atom>
        <atom name="AdmGUIDValue">80085</atom>
      </tuple>
    </table>
    <table name="DeaccessionDetails">
      <tuple>
        <atom name="DeaDeaccessionMethod"></atom>
        <atom name="DeaDeaccessionDate"></atom>
        <atom name="DeaDeaccessionNotes">John Teramoto, IMA Curator of Asian Art, this is a late printing.</atom>
        <tuple name="DeaReceivingPartyRef">
            <atom name="irn"></atom>
        </tuple>
        <atom name="DeaTransferNotes"></atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2022-06-07</atom>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="irn">16356</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionNo">07.7</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitAccessionDate">1907-01-04</atom>
    <atom name="TitMainTitle">Whistler's Mother</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <table name="Creator">
      <tuple>
        <atom name="irn">737</atom>
        <atom name="CreRole">Artist</atom>
        <atom name="CreCreatorAfterFollower"></atom>
      </tuple>
      <tuple>
        <atom name="irn">612140</atom>
        <atom name="CreRole">Artist, after</atom>
        <atom name="CreCreatorAfterFollower">After</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated"></atom>
    <atom name="CreEarliestDate"></atom>
    <atom name="CreLatestDate"></atom>
    <atom name="CreDateDesigned"></atom>
    <atom name="CreEarliestDesignDate"></atom>
    <atom name="CreLatestDesignDate"></atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="CreLoc">
      <tuple>
        <atom name="CreCountry">United States</atom>
      </tuple>
    </table>
    <atom name="TitObjectType">Visual Works: Prints</atom>
    <table name="ObjType">
      <tuple>
        <atom name="PhyMediaCategory">prints</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">engravings</atom>
      </tuple>
    </table>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">ink</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">paper</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">ink on paper, wood engraving</atom>
    <atom name="PhyTechnique">engraving {printing process}</atom>
    <atom name="PhyStyle"></atom>
    <table name="MarkType">
      <tuple>
        <atom name="CreMarkType">Signature</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions">Signed in pencil, below image, lower right: Henry Wolf sculpt</atom>
    <atom name="PhyConvertedDims">8 x 9-1/16 in. (image)
11-1/4 x 12-1/4 in. (sheet)</atom>
    <table name="Dims">
      <tuple>
        <atom name="PhyType">Image Dimensions</atom>
        <atom name="PhyHeight">8.0000</atom>
        <atom name="PhyWidth">9.0625</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 20.32 x 23.02 (image)</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Sheet Dimensions</atom>
        <atom name="PhyHeight">11.2500</atom>
        <atom name="PhyWidth">12.2500</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 28.57 x 21.11 (sheet)</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">John Herron Fund</atom>
    <table name="Rights">
      <tuple>
        <atom name="irn">807</atom>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <table name="RightsURIs">
      <tuple>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">904.1-Prints, Drawings, and Photographs</atom>
    <atom name="LocMovementType">Inventory Beginning 2018 - ten year schedule for upcoming reaccreditation</atom>
    <table name="CurLoc">
      <tuple>
        <tuple name="LocCurrentLocationRef">
          <atom name="irn">8644</atom>
          <atom name="LocLocationCode">F25.cg2.r5.lv14</atom>
          <atom name="LocLevel1">IMA</atom>
          <atom name="LocLevel2">Print Storage</atom>
          <atom name="LocLevel3">F25</atom>
          <atom name="LocLevel4">cg2</atom>
          <atom name="LocLevel5">r5</atom>
          <atom name="LocLevel6">lv14</atom>
          <atom name="LocLevel7"></atom>
          <atom name="LocLevel8"></atom>
        </tuple>
      </tuple>
    </table>
    <table name="PermLoc">
      <tuple>
        <tuple name="LocPermanentLocationRef">
          <atom name="irn">8644</atom>
          <atom name="LocLocationCode">F25.cg2.r5.lv14</atom>
          <atom name="LocLevel1">IMA</atom>
          <atom name="LocLevel2">Print Storage</atom>
          <atom name="LocLevel3">F25</atom>
          <atom name="LocLevel4">cg2</atom>
          <atom name="LocLevel5">r5</atom>
          <atom name="LocLevel6">lv14</atom>
          <atom name="LocLevel7"></atom>
          <atom name="LocLevel8"></atom>
        </tuple>
      </tuple>
    </table>
    <table name="GUIDs">
      <tuple>
        <atom name="AdmGUIDIsPreferred">No</atom>
        <atom name="AdmGUIDType">Dagwood ID</atom>
        <atom name="AdmGUIDValue">80096</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2022-06-07</atom>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="irn">47035</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionNo">08.19</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitAccessionDate">1908</atom>
    <atom name="TitMainTitle">Statue of Augustus Caesar</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <table name="Creator">
      <tuple>
        <atom name="irn">2741</atom>
        <atom name="CreRole">Artist</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">before 1908</atom>
    <atom name="CreEarliestDate"></atom>
    <atom name="CreLatestDate">1908</atom>
    <atom name="CreDateDesigned"></atom>
    <atom name="CreEarliestDesignDate"></atom>
    <atom name="CreLatestDesignDate"></atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <atom name="TitObjectType">Visual Works: Sculpture</atom>
    <table name="ObjType">
      <tuple>
        <atom name="PhyMediaCategory">reproductions</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">sculptures</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">casts</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">plaster</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">plaster cast</atom>
    <atom name="PhyTechnique">casting</atom>
    <atom name="PhyStyle">Roman</atom>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="PhyConvertedDims">87 in.</atom>
    <table name="Dims">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">87.0000</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Gift of Mary E. Nicholson</atom>
    <table name="Rights">
      <tuple>
        <atom name="irn">808</atom>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <table name="RightsURIs">
      <tuple>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">901.2-American Painting and Sculpture 1800-1945</atom>
    <atom name="LocMovementType">Inventory 2014-2015</atom>
    <table name="CurLoc">
      <tuple>
        <tuple name="LocCurrentLocationRef">
          <atom name="irn">87</atom>
          <atom name="LocLocationCode">On Loan</atom>
          <atom name="LocLevel1">On Loan</atom>
          <atom name="LocLevel2"></atom>
          <atom name="LocLevel3"></atom>
          <atom name="LocLevel4"></atom>
          <atom name="LocLevel5"></atom>
          <atom name="LocLevel6"></atom>
          <atom name="LocLevel7"></atom>
          <atom name="LocLevel8"></atom>
        </tuple>
      </tuple>
    </table>
    <atom name="AdmDateModified">2022-04-26</atom>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="irn">89724</atom>
    <table name="Flags">
      <tuple>
        <atom name="TitObjectRating">Blanket Record</atom>
      </tuple>
    </table>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionNo">09.28A-C</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitAccessionDate">1909-01-25</atom>
    <atom name="TitMainTitle">Biblesche Figuren</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <table name="Creator">
      <tuple>
        <atom name="irn">2108</atom>
        <atom name="CreRole">Artist</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1565</atom>
    <atom name="CreEarliestDate">1565</atom>
    <atom name="CreLatestDate">1565</atom>
    <atom name="CreDateDesigned"></atom>
    <atom name="CreEarliestDesignDate"></atom>
    <atom name="CreLatestDesignDate"></atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="CreLoc">
      <tuple>
        <atom name="CreCountry">Germany</atom>
      </tuple>
    </table>
    <atom name="TitObjectType">Visual Works: Prints</atom>
    <table name="ObjType">
      <tuple>
        <atom name="PhyMediaCategory">prints</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">engravings</atom>
      </tuple>
    </table>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">ink</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">paper</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">engraving, ink on paper</atom>
    <atom name="PhyTechnique">engraving {printing process}</atom>
    <atom name="PhyStyle"></atom>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="PhyConvertedDims">3-1/8 x 4-5/8 in.</atom>
    <table name="Dims">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">3.1250</atom>
        <atom name="PhyWidth">4.6200</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 7.93 x 11.74</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Gift of Mrs. Anna J. Brownell and Miss Frances J. Brownell</atom>
    <table name="Rights">
      <tuple>
        <atom name="irn">807</atom>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <table name="RightsURIs">
      <tuple>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">904.1-Prints, Drawings, and Photographs</atom>
    <atom name="LocMovementType"></atom>
    <table name="CurLoc">
      <tuple>
        <tuple name="LocCurrentLocationRef">
          <atom name="irn">68</atom>
          <atom name="LocLocationCode">see related parts</atom>
          <atom name="LocLevel1">IMA</atom>
          <atom name="LocLevel2">see related parts</atom>
          <atom name="LocLevel3"></atom>
          <atom name="LocLevel4"></atom>
          <atom name="LocLevel5"></atom>
          <atom name="LocLevel6"></atom>
          <atom name="LocLevel7"></atom>
          <atom name="LocLevel8"></atom>
        </tuple>
      </tuple>
    </table>
    <table name="PermLoc">
      <tuple>
        <tuple name="LocPermanentLocationRef">
          <atom name="irn">9898</atom>
          <atom name="LocLocationCode">F25.cg4.r15.lv3</atom>
          <atom name="LocLevel1">IMA</atom>
          <atom name="LocLevel2">Print Storage</atom>
          <atom name="LocLevel3">F25</atom>
          <atom name="LocLevel4">cg4</atom>
          <atom name="LocLevel5">r15</atom>
          <atom name="LocLevel6">lv3</atom>
          <atom name="LocLevel7"></atom>
          <atom name="LocLevel8"></atom>
        </tuple>
      </tuple>
    </table>
    <atom name="AdmDateModified">2019-06-14</atom>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="irn">16168</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionNo">09.28C</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitAccessionDate">1909-01-25</atom>
    <atom name="TitMainTitle">Jesus and the Apostles</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <table name="Creator">
      <tuple>
        <atom name="irn">2741</atom>
        <atom name="CreRole">Artist</atom>
      </tuple>
    </table>
    <table name="Culture">
      <tuple>
        <atom name="CreCreationNationality2">German</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">16th century</atom>
    <atom name="CreEarliestDate">1501</atom>
    <atom name="CreLatestDate">1600</atom>
    <atom name="CreDateDesigned"></atom>
    <atom name="CreEarliestDesignDate"></atom>
    <atom name="CreLatestDesignDate"></atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="CreLoc">
      <tuple>
        <atom name="CreCountry">Germany</atom>
      </tuple>
    </table>
    <atom name="TitObjectType">Visual Works: Prints</atom>
    <table name="ObjType">
      <tuple>
        <atom name="PhyMediaCategory">prints</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">woodcuts</atom>
      </tuple>
    </table>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">ink</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">paper</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">ink on paper, woodblock print</atom>
    <atom name="PhyTechnique">woodcutting</atom>
    <atom name="PhyStyle"></atom>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="PhyConvertedDims">4-3/8 x 5-1/2 in.</atom>
    <table name="Dims">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">4.3750</atom>
        <atom name="PhyWidth">5.5000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 11.11 x 13.96</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Gift of Mrs. Anna J. Brownell and Miss Frances J. Brownell</atom>
    <table name="Rights">
      <tuple>
        <atom name="irn">807</atom>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <table name="RightsURIs">
      <tuple>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">904.1-Prints, Drawings, and Photographs</atom>
    <atom name="LocMovementType">Inventory</atom>
    <table name="CurLoc">
      <tuple>
        <tuple name="LocCurrentLocationRef">
          <atom name="irn">9966</atom>
          <atom name="LocLocationCode">F25.cg4.r15.lv4</atom>
          <atom name="LocLevel1">IMA</atom>
          <atom name="LocLevel2">Print Storage</atom>
          <atom name="LocLevel3">F25</atom>
          <atom name="LocLevel4">cg4</atom>
          <atom name="LocLevel5">r15</atom>
          <atom name="LocLevel6">lv4</atom>
          <atom name="LocLevel7"></atom>
          <atom name="LocLevel8"></atom>
        </tuple>
      </tuple>
    </table>
    <table name="PermLoc">
      <tuple>
        <tuple name="LocPermanentLocationRef">
          <atom name="irn">9966</atom>
          <atom name="LocLocationCode">F25.cg4.r15.lv4</atom>
          <atom name="LocLevel1">IMA</atom>
          <atom name="LocLevel2">Print Storage</atom>
          <atom name="LocLevel3">F25</atom>
          <atom name="LocLevel4">cg4</atom>
          <atom name="LocLevel5">r15</atom>
          <atom name="LocLevel6">lv4</atom>
          <atom name="LocLevel7"></atom>
          <atom name="LocLevel8"></atom>
        </tuple>
      </tuple>
    </table>
    <table name="Parent">
      <tuple>
        <tuple name="AssParentObjectRef">
          <atom name="irn">89724</atom>
        </tuple>
      </tuple>
    </table>
    <table name="Related">
      <tuple>
        <atom name="irn">20184</atom>
      </tuple>
      <tuple>
        <atom name="irn">35937</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2019-06-14</atom>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <atom name="irn">21288</atom>
    <table name="Flags">
      <tuple>
        <atom name="TitObjectRating">Diversity Cataloging Project</atom>
      </tuple>
      <tuple>
        <atom name="TitObjectRating">Male</atom>
      </tuple>
      <tuple>
        <atom name="TitObjectRating">White</atom>
      </tuple>
    </table>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionNo">10.8</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitAccessionDate">1910-05-12</atom>
    <atom name="TitMainTitle">Portrait of William Merritt Chase</atom>