<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           elocations
    integer         irn
    text short      AdmPublishWebNoPassword
    text short      LocLocationCode
    text short      LocLevel1
    text short      LocLevel2
    text short      LocLevel3
    text short      LocLevel4
    text short      LocLevel5
    text short      LocLevel6
    text short      LocLevel7
    text short      LocLevel8
    date            AdmDateModified
  end
?>
<!-- Data -->
<table name="elocations">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">738</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Ac1.lv1</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Ac1</atom>
    <atom name="LocLevel4">lv1</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-26</atom>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="irn">2351</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.63w</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">63w</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="irn">14099</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">W302.c7.riser</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Eiteljorg Suite of African and Oceanic Art</atom>
    <atom name="LocLevel3">W302</atom>
    <atom name="LocLevel4">c7</atom>
    <atom name="LocLevel5">riser</atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2012-12-27</atom>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="irn">9733</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.cg14.r7.lv9</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">cg14</atom>
    <atom name="LocLevel5">r7</atom>
    <atom name="LocLevel6">lv9</atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2006-08-28</atom>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="irn">773</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Ec43.lv6</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Ec43</atom>
    <atom name="LocLevel4">lv6</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-26</atom>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="irn">3674</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.10w</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">10w</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <atom name="irn">14787</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">K212</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Andrew and Jane Paine Galleries</atom>
    <atom name="LocLevel3">K212</atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2013-01-25</atom>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <atom name="irn">3484</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.170e</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">170e</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 9 -->
  <tuple>
    <atom name="irn">15826</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.sc1.lv10</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">sc1</atom>
    <atom name="LocLevel5">lv10</atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2021-04-05</atom>
  </tuple>

  <!-- Row 10 -->
  <tuple>
    <atom name="irn">1095</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Ec45.lv3</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Ec45</atom>
    <atom name="LocLevel4">lv3</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-26</atom>
  </tuple>

  <!-- Row 11 -->
  <tuple>
    <atom name="irn">7919</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Tc58.lv8</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Tc58</atom>
    <atom name="LocLevel4">lv8</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-07-08</atom>
  </tuple>

  <!-- Row 12 -->
  <tuple>
    <atom name="irn">7246</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Tc58.lv2</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Tc58</atom>
    <atom name="LocLevel4">lv2</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-07-08</atom>
  </tuple>

  <!-- Row 13 -->
  <tuple>
    <atom name="irn">4348</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Tc23.lv1</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Tc23</atom>
    <atom name="LocLevel4">lv1</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-07-08</atom>
  </tuple>

  <!-- Row 14 -->
  <tuple>
    <atom name="irn">3965</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.92w</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">92w</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 15 -->
  <tuple>
    <atom name="irn">9966</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.cg4.r15.lv4</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">cg4</atom>
    <atom name="LocLevel5">r15</atom>
    <atom name="LocLevel6">lv4</atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2009-06-18</atom>
  </tuple>

  <!-- Row 16 -->
  <tuple>
    <atom name="irn">8644</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.cg2.r5.lv14</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">cg2</atom>
    <atom name="LocLevel5">r5</atom>
    <atom name="LocLevel6">lv14</atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2006-08-22</atom>
  </tuple>

  <!-- Row 17 -->
  <tuple>
    <atom name="irn">35</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Ec43.lv4</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Ec43</atom>
    <atom name="LocLevel4">lv4</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-26</atom>
  </tuple>

  <!-- Row 18 -->
  <tuple>
    <atom name="irn">9474</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.bin8.lv1.sl6</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">bin8</atom>
    <atom name="LocLevel5">lv1</atom>
    <atom name="LocLevel6">sl6</atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2006-08-21</atom>
  </tuple>

  <!-- Row 19 -->
  <tuple>
    <atom name="irn">7349</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.172w</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">172w</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 20 -->
  <tuple>
    <atom name="irn">14784</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="LocLocationCode">K210</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Joan D. Weisenberger Gallery</atom>
    <atom name="LocLevel3">K210</atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2013-09-12</atom>
  </tuple>

  <!-- Row 21 -->
  <tuple>
    <atom name="irn">7243</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Tc58.lv7</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Tc58</atom>
    <atom name="LocLevel4">lv7</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-07-08</atom>
  </tuple>

  <!-- Row 22 -->
  <tuple>
    <atom name="irn">3351</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.17w</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">17w</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 23 -->
  <tuple>
    <atom name="irn">7328</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.81w</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">81w</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 24 -->
  <tuple>
    <atom name="irn">14825</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">W202</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Pulliam Family Great Hall</atom>
    <atom name="LocLevel3">W202</atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2013-01-28</atom>
  </tuple>

  <!-- Row 25 -->
  <tuple>
    <atom name="irn">10315</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.cg5.r6.lv4</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">cg5</atom>
    <atom name="LocLevel5">r6</atom>
    <atom name="LocLevel6">lv4</atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2009-06-18</atom>
  </tuple>

  <!-- Row 26 -->
  <tuple>
    <atom name="irn">9972</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.cg6.r4.lv12</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">cg6</atom>
    <atom name="LocLevel5">r4</atom>
    <atom name="LocLevel6">lv12</atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2009-06-18</atom>
  </tuple>

  <!-- Row 27 -->
  <tuple>
    <atom name="irn">68</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">see related parts</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">see related parts</atom>
    <atom name="LocLevel3"></atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-03-24</atom>
  </tuple>

  <!-- Row 28 -->
  <tuple>
    <atom name="irn">2634</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.cs7.lv8</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">cs7</atom>
    <atom name="LocLevel5">lv8</atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2013-01-16</atom>
  </tuple>

  <!-- Row 29 -->
  <tuple>
    <atom name="irn">9682</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.cg6.r8.lv4</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">cg6</atom>
    <atom name="LocLevel5">r8</atom>
    <atom name="LocLevel6">lv4</atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2009-06-18</atom>
  </tuple>

  <!-- Row 30 -->
  <tuple>
    <atom name="irn">1050</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.18w</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">18w</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 31 -->
  <tuple>
    <atom name="irn">14746</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">C207</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Portraiture, Medieval  Art Gallery</atom>
    <atom name="LocLevel3">C207</atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2019-04-02</atom>
  </tuple>

  <!-- Row 32 -->
  <tuple>
    <atom name="irn">9950</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">T13</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Exhibition Holding</atom>
    <atom name="LocLevel3">T13</atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2006-08-18</atom>
  </tuple>

  <!-- Row 33 -->
  <tuple>
    <atom name="irn">6378</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.91w</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">91w</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 34 -->
  <tuple>
    <atom name="irn">14916</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Location Not Verified</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Location Not Verified</atom>
    <atom name="LocLevel3"></atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2013-01-29</atom>
  </tuple>

  <!-- Row 35 -->
  <tuple>
    <atom name="irn">87</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">On Loan</atom>
    <atom name="LocLevel1">On Loan</atom>
    <atom name="LocLevel2"></atom>
    <atom name="LocLevel3"></atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2006-03-15</atom>
  </tuple>

  <!-- Row 36 -->
  <tuple>
    <atom name="irn">136</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Cc3.lv3</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Cc3</atom>
    <atom name="LocLevel4">lv3</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-07-08</atom>
  </tuple>

  <!-- Row 37 -->
  <tuple>
    <atom name="irn">10285</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.cg5.r3.lv11</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">cg5</atom>
    <atom name="LocLevel5">r3</atom>
    <atom name="LocLevel6">lv11</atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2009-06-18</atom>
  </tuple>

  <!-- Row 38 -->
  <tuple>
    <atom name="irn">10326</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.cg5.r7.lv13</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">cg5</atom>
    <atom name="LocLevel5">r7</atom>
    <atom name="LocLevel6">lv13</atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2009-06-18</atom>
  </tuple>

  <!-- Row 39 -->
  <tuple>
    <atom name="irn">9921</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">F25.cg10.r2.lv1</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Print Storage</atom>
    <atom name="LocLevel3">F25</atom>
    <atom name="LocLevel4">cg10</atom>
    <atom name="LocLevel5">r2</atom>
    <atom name="LocLevel6">lv1</atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2006-08-28</atom>
  </tuple>

  <!-- Row 40 -->
  <tuple>
    <atom name="irn">8358</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">LH103.c5.lv2</atom>
    <atom name="LocLevel1">Lilly House</atom>
    <atom name="LocLevel2">Game room</atom>
    <atom name="LocLevel3">LH103</atom>
    <atom name="LocLevel4">c5</atom>
    <atom name="LocLevel5">lv2</atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2006-10-06</atom>
  </tuple>

  <!-- Row 41 -->
  <tuple>
    <atom name="irn">3715</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.174w</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">174w</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 42 -->
  <tuple>
    <atom name="irn">14123</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">W303.c1.wall</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Eiteljorg Suite of African and Oceanic Art</atom>
    <atom name="LocLevel3">W303</atom>
    <atom name="LocLevel4">c1</atom>
    <atom name="LocLevel5">wall</atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2012-12-27</atom>
  </tuple>

  <!-- Row 43 -->
  <tuple>
    <atom name="irn">14069</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">H302</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Contemporary Design Gallery</atom>
    <atom name="LocLevel3">H302</atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2019-04-02</atom>
  </tuple>

  <!-- Row 44 -->
  <tuple>
    <atom name="irn">15153</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Hc2.lv7</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Hc2</atom>
    <atom name="LocLevel4">lv7</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2013-11-12</atom>
  </tuple>

  <!-- Row 45 -->
  <tuple>
    <atom name="irn">452</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">ANP</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">The Virginia B. Fairbanks Art &amp; Nature Park</atom>
    <atom name="LocLevel3"></atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2010-06-17</atom>
  </tuple>

  <!-- Row 46 -->
  <tuple>
    <atom name="irn">14999</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="LocLocationCode">H301</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Contemporary Design Gallery</atom>
    <atom name="LocLevel3">H301</atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2013-09-12</atom>
  </tuple>

  <!-- Row 47 -->
  <tuple>
    <atom name="irn">1083</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Tc25.lv9</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Tc25</atom>
    <atom name="LocLevel4">lv9</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-07-08</atom>
  </tuple>

  <!-- Row 48 -->
  <tuple>
    <atom name="irn">326</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">G</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Grounds</atom>
    <atom name="LocLevel3">G</atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2019-05-06</atom>
  </tuple>

  <!-- Row 49 -->
  <tuple>
    <atom name="irn">10</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Returned</atom>
    <atom name="LocLevel1">Returned</atom>
    <atom name="LocLevel2"></atom>
    <atom name="LocLevel3"></atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2006-04-13</atom>
  </tuple>

  <!-- Row 50 -->
  <tuple>
    <atom name="irn">14628</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="LocLocationCode">H203.p2</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">Mary Ann and Gene Zink Gallery</atom>
    <atom name="LocLevel3">H203</atom>
    <atom name="LocLevel4">p2</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2013-09-12</atom>
  </tuple>

  <!-- Row 51 -->
  <tuple>
    <atom name="irn">8013</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Lc8.lv4</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Lc8</atom>
    <atom name="LocLevel4">lv4</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-07-08</atom>
  </tuple>

  <!-- Row 52 -->
  <tuple>
    <atom name="irn">319</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Tc46</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Tc46</atom>
    <atom name="LocLevel4"></atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-07-08</atom>
  </tuple>

  <!-- Row 53 -->
  <tuple>
    <atom name="irn">4562</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">P.72e</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">P</atom>
    <atom name="LocLevel4">72e</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-06-25</atom>
  </tuple>

  <!-- Row 54 -->
  <tuple>
    <atom name="irn">15193</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Hc9.lv4</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Hc9</atom>
    <atom name="LocLevel4">lv4</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2013-11-12</atom>
  </tuple>

  <!-- Row 55 -->
  <tuple>
    <atom name="irn">663</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="LocLocationCode">Xc4.lv5</atom>
    <atom name="LocLevel1">IMA</atom>
    <atom name="LocLevel2">storage</atom>
    <atom name="LocLevel3">Xc4</atom>
    <atom name="LocLevel4">lv5</atom>
    <atom name="LocLevel5"></atom>
    <atom name="LocLevel6"></atom>
    <atom name="LocLevel7"></atom>
    <atom name="LocLevel8"></atom>
    <atom name="AdmDateModified">2008-07-08</atom>
  </tuple>

  <!-- Row 56 -->
  <tuple>
    <atom name="irn">19</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>