<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           enarratives
    integer         irn
    text short      AdmPublishWebNoPassword
    text long       NarTitle
    text short      DesPurpose
    table           NarDate0
      date            NarDate
    end
    text long       NarNarrative
    table           authors
      integer         irn
      date            AdmDateModified
    end
    table           objects
      integer         irn
      date            AdmDateModified
    end
    table           events
      integer         irn
      date            AdmDateModified
    end
    table           parties
      integer         irn
      date            AdmDateModified
    end
    date            AdmDateModified
  end
?>
<!-- Data -->
<table name="enarratives">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">309</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">16.924A-C_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;The play is a story of love, jealousy, intrigue and revenge revolving around a sword offered to the Kiyomizu temple on behalf of the shogun. The assistant on the left "accidentally" swings his mallet towards his rival, the assistant on the right, but the master deflects the strike.&lt;/p&gt; &lt;p&gt;The edges of the sheets are somewhat tattered, but the mat hides them. The prints are soiled, and the inking is incomplete in some areas. Nevertheless, the clear and decisive composition, the dramatic poses and strong, emotional facial expressions together create a powerful visual image.&lt;/p&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">25098</atom>
        <atom name="AdmDateModified">2022-02-23</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-07-28</atom>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="irn">623</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">1989.1569_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;The prominent face on this bowl depicts a European, specifically a Portuguese man.  Depictions of Portuguese, the first Europeans to visit the Benin Kingdom in the late 1400's, are considered positive images on Benin royal objects.  The Portuguese, who at one time were allies with the Benin Kingdom, symbolize wealth and power.&lt;/p&gt; &lt;p&gt;Brass casters were influenced by imported bowls, boxes and other types of objects acquired through coastal trade with Europeans.  Although this bowl, which is missing its lid, was made by Benin brass casters, its shape is clearly derived from European bowls.  The application of gold to the surface is unusual in Benin art and the technology was probably learned from European visitors.&lt;/p&gt; &lt;p&gt;A pattern of interlacing lines is a popular design element in Benin art.  It can be seen on the rim, stem and base of this bowl and on other Benin objects.&lt;/p&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">1105</atom>
        <atom name="AdmDateModified">2022-02-23</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-07-30</atom>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="irn">1665</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">2007.4A-B_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;In former times an ear piercing ceremony was performed on every child before puberty. The earlobe was pierced with a sharp piece of iron. Pieces of corn stalk were placed in the holes, and as the ear healed larger and larger pieces were put into the hole until it was large enough to accommodate earplugs.&lt;/p&gt; &lt;p&gt;The distended earlobes were adorned in early times with circular plugs of wood, sometimes decorated with metal studs. From about 1950 to 1970 pieces of synthetic floor covering were applied in mosaic fashion to one or both sides of the earplugs. The colors relate to those of traditional Zulu beadwork, and some color combinations may indicate clan affiliation or other aspects of an individual.&lt;/p&gt; &lt;p&gt;The long standing Zulu practice of wearing earplugs is associated with both men and women. Today, people increasingly relate the stretching of earlobes with a lack of sophistication, and the wearing of earplugs is falling out of fashion.&lt;/p&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">64017</atom>
        <atom name="AdmDateModified">2020-04-10</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-08-04</atom>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="irn">2568</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">74.10_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;The first Amish immigrants from Germany and Switzerland settles in Lancaster County in eastern Pennsylvania at the beginning of the eighteenth century. Simplicity characterized their lives, and their religious beliefs prohibited them from possessing worldly and decorative items.&lt;/p&gt; &lt;p&gt;Although quilts were made for utilitarian purposes, they provided Amish women with an artistic outlet that allowed their creativity to flourish. One of the oldest and most common designs in Amish quilts of Pennsylvania is a large-scale diamond enclosed by a square. The diamond, and old German motif and often a symbol of Christ, represents order, discipline and fundamental values honored by the Amish.&lt;/p&gt; &lt;p&gt;Since the use of printed fabrics was prohibited in Amish culture, solid color fabrics in saturated hues were often used. The quilting is executed in a variety of feather patterns. A feathered Wreath is depicted in the center of the diamond and also the outer border of the quilt. The inner border id quilted in the Rope pattern. Bold and simple designs combined with dramatic colors and excellent workmanship are characteristic of Amish quilts.&lt;/p&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">17425</atom>
        <atom name="AdmDateModified">2019-06-14</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-08-06</atom>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="irn">2594</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">75.107_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;Patriotic themes and motifs have been incorporated into quilt designs since the Revolutionary War, 1775-1783. Union quilts, featuring the American eagle, were popular from the late 1780s until the 1840s and again during the Civil War. The design of this impressive quilt, dated 1853, was influenced by early nineteenth-century patriotic quilts and reflects the growing political tensions in antebellum America.&lt;/p&gt; &lt;p&gt;The quilt depicts a stylized central eagle, surrounded by a wreath of thirteen stars. From the eagle’s beak floats a streamer with the Latin mottom &lt;em&gt;E Plubribus Unum&lt;/em&gt;, which means “one out of many”.&lt;/p&gt; &lt;p&gt;The eagle, the stars and the floral borders are appliquéd. The center of each pieced star is embroidered with the name of one of the thirteen original states: New Hampshire, Massachusetts, Rhode Island, Connecticut, New York, New Jersey, Delaware, Pennsylvania, Maryland, Virginia, North Carolina, South Carolina and Georgia.&lt;/p&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">8543</atom>
        <atom name="AdmDateModified">2019-06-14</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-08-06</atom>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="irn">2774</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">80.262A-C_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;Halston said, "I love the idea of a ruffle that seems to come from nothing. I like things that look sculptured and yet are soft." The period from late 1970s to early 1980s is known as Halston's ruffle period. In 1980 &lt;em&gt;Women Wear Daily&lt;/em&gt; gave Halston a new nickname, "Mr. Ruffle."&lt;/p&gt; &lt;p&gt;In Halston's innovative construction technique, the ruffles and body of the garment were created from one piece of fabric. This softly draped blouse with cut-in-one ruffles was created by cutting several layers of ruffles in minimally graduated widths to create a soft fluttery look.&lt;/p&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">24892</atom>
        <atom name="AdmDateModified">2019-06-13</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-08-06</atom>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <atom name="irn">2917</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">C10063_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;Over the course of more than forty years, Rembrandt portrayed his own likeness at least seventy-five times. In this highly unconventional work, painted when Rembrandt was in his early twenties, the artist casts much of his face in deep shadow and obscures most of its outward appearance. His lips parted in spontaneous speech and his eyes all but invisible, Rembrandt's self-portrait conveys an intense preoccupation with his own artistic identity and inner imagination.&lt;/p&gt; &lt;blockquote&gt;&lt;em&gt;Study your emotions in front of a mirror, where you can be both performer and beholder.&lt;/em&gt;&lt;br /&gt;-Samuel van Hoogstraten, 1678&lt;/blockquote&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">33140</atom>
        <atom name="AdmDateModified">2022-04-05</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-08-06</atom>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <atom name="irn">3134</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="NarTitle">55.26_v02</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;FONT size=1&gt;
&lt;P&gt;&lt;FONT size=3&gt;Here the sun sets over the rich, green, prairie landscape. A bright orange orb suggests the end of a hot summer day.&lt;/FONT&gt;&lt;/P&gt;
&lt;P&gt;&lt;FONT size=3&gt;This painting is characteristic of the flatness and horizontality of the landscape.&lt;/FONT&gt;&lt;/P&gt;
&lt;P&gt;&lt;FONT size=3&gt;Prairie Dell is an area in Prairie Township, not far from Adam's home in Muncie, Indiana.&lt;/FONT&gt;&lt;/P&gt;&lt;/FONT&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">17123</atom>
        <atom name="AdmDateModified">2022-03-28</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-09-08</atom>
  </tuple>

  <!-- Row 9 -->
  <tuple>
    <atom name="irn">6633</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">14.55_v01</atom>
    <atom name="DesPurpose">Exhibition Label</atom>
    <table name="NarDate0">
      <tuple>
        <atom name="NarDate">2015-12-18</atom>
      </tuple>
    </table>
    <atom name="NarNarrative">&lt;UL&gt;
&lt;LI&gt;The contents of Fiscus’s well-appointed workspace—leather-bound books, ceramic &lt;EM&gt;objets d’art,&lt;/EM&gt; and a fur throw—provide the motif for this composition and demonstrate his ability to depict various textures. His range of subject matter is suggested by the charcoal portrait sketch, the fruit still-life painting, and the complex figural scene.&lt;BR&gt;&lt;/LI&gt;
&lt;LI&gt;The teenaged artist thrived under the tutelage of Love and Gookins. A writer of the period observed: “Charles Fiscus was among the most talented pupils of [the] early school….”&lt;BR&gt;&lt;/LI&gt;
&lt;LI&gt;After the Indiana School of Art shuttered its doors, Fiscus continued his studies under Gookins in Terre Haute and Chicago. Later, he participated in Indianapolis’s sketching groups until his untimely death at age 22.&lt;/LI&gt;&lt;/UL&gt;</atom>
    <table name="authors">
      <tuple>
        <atom name="irn">9711</atom>
        <atom name="AdmDateModified">2022-03-02</atom>
      </tuple>
    </table>
    <table name="objects">
      <tuple>
        <atom name="irn">1065</atom>
        <atom name="AdmDateModified">2022-05-16</atom>
      </tuple>
    </table>
    <table name="events">
      <tuple>
        <atom name="irn">4357</atom>
        <atom name="AdmDateModified">2021-08-27</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2017-01-09</atom>
  </tuple>

  <!-- Row 10 -->
  <tuple>
    <atom name="irn">8573</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">55.26_v03</atom>
    <atom name="DesPurpose">Object Label</atom>
    <table name="NarDate0">
      <tuple>
        <atom name="NarDate">2017-08-07</atom>
      </tuple>
    </table>
    <atom name="NarNarrative">&lt;UL&gt;
&lt;LI&gt;The oppressively hot and heavy air on the horizon during the dog days of summer casts an orange haze on the setting sun, which is reflected in the pools of water below.&lt;BR&gt;&lt;/LI&gt;
&lt;LI&gt;In a response to his environment, Adams drew the flat lines and planes of his painting directly from the prairie landscape around him. This provided an overall flatness to the image, where even the trees become a horizontal stripe in his composition.&lt;BR&gt;&lt;/LI&gt;
&lt;LI&gt;Adams settled in Muncie after studying art in Munich, Germany. The grassy prairies of northern Indiana became his purview, as his fellow Indiana artists preferred the forests and hills to the south.He would later also turned his gaze southward and establish a studio in Brookville, Indiana.&lt;/LI&gt;&lt;/UL&gt;</atom>
    <table name="authors">
      <tuple>
        <atom name="irn">10748</atom>
        <atom name="AdmDateModified">2021-01-28</atom>
      </tuple>
    </table>
    <table name="objects">
      <tuple>
        <atom name="irn">17123</atom>
        <atom name="AdmDateModified">2022-03-28</atom>
      </tuple>
    </table>
    <table name="events">
      <tuple>
        <atom name="irn">5014</atom>
        <atom name="AdmDateModified">2017-09-09</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2017-08-24</atom>
  </tuple>

  <!-- Row 11 -->
  <tuple>
    <atom name="irn">2269</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="NarTitle">55.26_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;This scene depicts the flat grasslands of Prairie Township near Adams’s Muncie, Indiana, home. A hazy expanse of green fills the foreground while darker-toned tree silhouettes occupy the horizon line, providing an overall flatness to the landscape. A simple disc of blazing orange suggests sunset at the end of a hot summer day.&lt;/p&gt; &lt;p&gt;Adams settled in Muncie after seven years at the Royal Academy of Fine Arts in Munich, Germany. In 1897 he and his wife—Winifred Brady, who was also a painter—moved to Brookville, Indiana. There they lived with T.C. Steele in an old house nicknamed the “The Hermitage.”&lt;/p&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">17123</atom>
        <atom name="AdmDateModified">2022-03-28</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2017-08-24</atom>
  </tuple>

  <!-- Row 12 -->
  <tuple>
    <atom name="irn">2598</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">75.174_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;Over the past four years, Robert Indiana's LOVE sculpture has undergone a major overhaul to secure its structural integrity. With the structural repairs now successfully completed, the IMA is taking the final steps to restore its surface appearance.&lt;/p&gt; &lt;p&gt;Technicians recently used a fine air abrasive system to blast the sculpture's surface in order to remove the original textured, dark purple and rust corrosion, which had been marred as a result of the structural repairs. Over the next few years, the clean, freshly exposed Cor-ten steel will re-weather outside and the smooth steel will transform from silver to a variegated purplish brown patina with iridescent overtones. The first stage of this process may surprise viewers because the sculpture will turn birth orange due to rusting which results from the steel being exposed to repeated wet and dry cycles outdoors. The pace of the change in patina will depend on weather conditions, but eventually the object will turn brown and then continue darkening to its popular, recognizable appearance.&lt;/p&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">20419</atom>
        <atom name="AdmDateModified">2022-04-26</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-08-06</atom>
  </tuple>

  <!-- Row 13 -->
  <tuple>
    <atom name="irn">6641</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">94.1_v02</atom>
    <atom name="DesPurpose">Exhibition Label</atom>
    <table name="NarDate0">
      <tuple>
        <atom name="NarDate">2015-12-18</atom>
      </tuple>
    </table>
    <atom name="NarNarrative">&lt;UL&gt;
&lt;LI&gt;Urban and rural spaces, past and present, intermingle in this now iconic portrait of downtown Indianapolis. A tree-lined branch of the Central Canal, a pioneer waterway built in the 1830s, foregrounds the city’s skyline, which is tinged lavender in the morning light.&lt;BR&gt;&lt;/LI&gt;
&lt;LI&gt;The last decades of the 19th century witnessed the construction of the city’s most recognizable monuments: the State Capitol and the Soldiers and Sailors Monument. Both structures are present in the picture, though the latter had not yet been completed.&lt;BR&gt;&lt;/LI&gt;
&lt;LI&gt;Gruelle was self-taught. He had been employed decorating iron safes in Cincinnati when he found his calling. In 1882 he relocated to Indianapolis and devoted his time fully to painting the city and its environs.&lt;/LI&gt;&lt;/UL&gt;</atom>
    <table name="authors">
      <tuple>
        <atom name="irn">9711</atom>
        <atom name="AdmDateModified">2022-03-02</atom>
      </tuple>
    </table>
    <table name="objects">
      <tuple>
        <atom name="irn">37087</atom>
        <atom name="AdmDateModified">2022-05-19</atom>
      </tuple>
    </table>
    <table name="events">
      <tuple>
        <atom name="irn">4357</atom>
        <atom name="AdmDateModified">2021-08-27</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2017-01-09</atom>
  </tuple>

  <!-- Row 14 -->
  <tuple>
    <atom name="irn">2908</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="NarTitle">94.1_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;The subject of this work is the canal that runs through downtown Indianapolis.&lt;/p&gt; &lt;p&gt;The focal points of this canvas are the state capitol and the Civil War monument then under construction.&lt;/p&gt; &lt;p&gt;In this painting Gruelle alludes to both Indiana's history and its future.&lt;/p&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">37087</atom>
        <atom name="AdmDateModified">2022-05-19</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2017-01-09</atom>
  </tuple>

  <!-- Row 15 -->
  <tuple>
    <atom name="irn">3009</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="NarTitle">TR8666/2_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;div&gt; &lt;p&gt;Munich’s Royal Academy of Fine Arts did not teach landscape painting, so Steele pursued it independently while studying there. The Steele family rented a house in the rural town of Schleissheim, and the artist painted the surrounding countryside under the guidance of J. Frank Currier, an American expatriate with a bold, expressionist painting style.&lt;/p&gt; &lt;p&gt;&lt;em&gt;Evening Poplars &lt;/em&gt;was based on a sketch and completed in Steele’s studio. Not present in the original drawing was the solitary figure of a woman, which echoes the vertical lines of the dramatically backlit poplars that tower above.&lt;/p&gt; &lt;/div&gt; &lt;ul&gt; &lt;/ul&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">4634</atom>
        <atom name="AdmDateModified">2022-05-19</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-08-06</atom>
  </tuple>

  <!-- Row 16 -->
  <tuple>
    <atom name="irn">6638</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">29.93_v01</atom>
    <atom name="DesPurpose">Exhibition Label</atom>
    <table name="NarDate0">
      <tuple>
        <atom name="NarDate">2015-12-18</atom>
      </tuple>
    </table>
    <atom name="NarNarrative">&lt;UL&gt;
&lt;LI&gt;Faces ravaged by time and labor abound in the students’ sketchbooks at the Munich Academy. However, this figure study depicts a young girl, long-identified as the artist’s daughter Gretchen. Tailoring his style to the youthful sitter, Richards softened his dark palette with the addition of a pink scarf to her costume.&lt;BR&gt;&lt;/LI&gt;
&lt;LI&gt;The girl’s rigid, formal pose and carefully recorded features attest to the influence of local artist Wilhelm Leibl, who was active in Munich and the recognized leader in German realism.&lt;BR&gt;&lt;/LI&gt;
&lt;LI&gt;Richards’s preference for figure painting, as well as his refusal to reestablish residency in Indiana, set him apart from his Hoosier colleagues. He died of tuberculosis at the age of 40 in Denver.&lt;/LI&gt;&lt;/UL&gt;</atom>
    <table name="authors">
      <tuple>
        <atom name="irn">9711</atom>
        <atom name="AdmDateModified">2022-03-02</atom>
      </tuple>
    </table>
    <table name="objects">
      <tuple>
        <atom name="irn">18672</atom>
        <atom name="AdmDateModified">2022-02-18</atom>
      </tuple>
    </table>
    <table name="events">
      <tuple>
        <atom name="irn">4357</atom>
        <atom name="AdmDateModified">2021-08-27</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2017-01-09</atom>
  </tuple>

  <!-- Row 17 -->
  <tuple>
    <atom name="irn">92</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="NarTitle">10.8_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;P&gt;With his top hat, spats, and cane, Chase was one of the most dapper and cosmopolitan artists of his day.&lt;/P&gt;
&lt;P&gt;This portrait was cut down because a critic said the ship deck where Chase stood was “not in good perspective.”&lt;/P&gt;
&lt;P&gt;Beckwith and Chase returned from their studies abroad on the same ship in 1878.&lt;/P&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">21288</atom>
        <atom name="AdmDateModified">2022-05-19</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-08-06</atom>
  </tuple>

  <!-- Row 18 -->
  <tuple>
    <atom name="irn">3032</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">10.8_v02</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;P&gt;• Beckwith recorded painter William Merritt Chase in dapper travel attire, including spats and a cane. An arresting passage of brushwork draws attention to the subject’s bejeweled left hand. Chase strove to ennoble his profession by dressing impeccably.&lt;/P&gt;
&lt;P&gt;• Upon completion of their studies abroad, Beckwith and Chase set sail for the United States "to earn a living by their brushes," in Beckwith’s words. This 1878 transatlantic voyage cemented the artists’ friendship. Beckwith began sketches for this portrait of his friend while they were on another journey back to Europe. &lt;/P&gt;
&lt;P&gt;• In 1896 Beckwith cropped the picture in response to criticism of an error in perspective.&lt;/P&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">21288</atom>
        <atom name="AdmDateModified">2022-05-19</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2021-03-14</atom>
  </tuple>

  <!-- Row 19 -->
  <tuple>
    <atom name="irn">1910</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NarTitle">26.189_v01</atom>
    <atom name="DesPurpose">Object Label</atom>
    <atom name="NarNarrative">&lt;p&gt;This ambitious portrait presents the members of the Hoosier group, (from left to right) T. C. Steele, Otto Stark, J. Ottis Adams and William Forsyth.  Richard Gruelle had died seven years earlier.&lt;/p&gt; &lt;p&gt;The artists are posed as if they were choosing paintings for an art exhibition.&lt;/p&gt;</atom>
    <table name="objects">
      <tuple>
        <atom name="irn">29270</atom>
        <atom name="AdmDateModified">2022-06-08</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2015-08-04</atom>
  </tuple>
</table>
