<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           eparties
    integer         irn
    text short      AdmPublishWebNoPassword
    text short      NamPartyType
    text long       NamFullName
    text short      NamTitle
    text short      NamFirst
    text short      NamMiddle
    text short      NamLast
    text short      NamSuffix
    table           OtherPersonNames
      text short      NamOtherNames
    end
    text short      NamSex
    text short      BioNationality
    table           Identities
      text short      BioCulturalInfluences
    end
    text short      BioBirthDate
    date            BioBirthEarliestDate
    date            BioBirthLatestDate
    text short      BioBirthPlace
    text short      BioDeathDate
    date            BioDeathEarliestDate
    date            BioDeathLatestDate
    text short      BioDeathPlace
    text long       NamOrganisation
    text short      NamOrganisationAcronym
    table           OtherOrgNames
      text long       NamOrganisationOtherNames
    end
    text short      IMAHisCommenced
    date            IMAHisBeginEarliestDate
    date            IMAHisBeginLatestDate
    text short      IMAHisCompleted
    date            IMAHisEndEarliestDate
    date            IMAHisEndLatestDate
    text short      ColCollaborationName
    table           Collaborators
      text short      ColRole
      integer         irn
      date            AdmDateModified
    end
    table           Roles
      text short      NamRoles
    end
    table           GUIDs
      text short      AdmGUIDIsPreferred
      text short      AdmGUIDType
      text short      AdmGUIDValue
    end
    date            AdmDateModified
  end
?>
<!-- Data -->
<table name="eparties">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">733</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Registration Verified</atom>
    <atom name="NamFullName">Charles J. Fiscus</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst">Charles</atom>
    <atom name="NamMiddle">J.</atom>
    <atom name="NamLast">Fiscus</atom>
    <atom name="NamSuffix"></atom>
    <table name="OtherPersonNames">
      <tuple>
        <atom name="NamOtherNames">Fiscus, Charles Joseph</atom>
      </tuple>
    </table>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">American</atom>
    <table name="Identities">
      <tuple>
        <atom name="BioCulturalInfluences">Caucasian</atom>
      </tuple>
      <tuple>
        <atom name="BioCulturalInfluences">White</atom>
      </tuple>
    </table>
    <atom name="BioBirthDate">1861</atom>
    <atom name="BioBirthEarliestDate">1861</atom>
    <atom name="BioBirthLatestDate">1861</atom>
    <atom name="BioBirthPlace"></atom>
    <atom name="BioDeathDate">1884</atom>
    <atom name="BioDeathEarliestDate">1884</atom>
    <atom name="BioDeathLatestDate">1884</atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2022-02-18</atom>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="irn">5060</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Person</atom>
    <atom name="NamFullName">Paul E. Beem</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst">Paul</atom>
    <atom name="NamMiddle">Edward</atom>
    <atom name="NamLast">Beem</atom>
    <atom name="NamSuffix"></atom>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">American</atom>
    <atom name="BioBirthDate">1908</atom>
    <atom name="BioBirthEarliestDate">1908</atom>
    <atom name="BioBirthLatestDate">1908</atom>
    <atom name="BioBirthPlace">Indianapolis, Indiana</atom>
    <atom name="BioDeathDate">1979</atom>
    <atom name="BioDeathEarliestDate">1979</atom>
    <atom name="BioDeathLatestDate">1979</atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2019-01-10</atom>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="irn">2741</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Registration Verified</atom>
    <atom name="NamFullName">Unknown</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst"></atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast">Unknown</atom>
    <atom name="NamSuffix"></atom>
    <atom name="NamSex"></atom>
    <atom name="BioNationality"></atom>
    <atom name="BioBirthDate"></atom>
    <atom name="BioBirthEarliestDate"></atom>
    <atom name="BioBirthLatestDate"></atom>
    <atom name="BioBirthPlace"></atom>
    <atom name="BioDeathDate"></atom>
    <atom name="BioDeathEarliestDate"></atom>
    <atom name="BioDeathLatestDate"></atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">designer</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">Origin</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">manufacturer</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">publisher</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">author</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">Culture or People</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">printer</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">photographer</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">Maker</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">Maker</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">Creator</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2019-05-09</atom>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="irn">610521</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Place Holder</atom>
    <atom name="NamFullName">James Thornhill</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst">James</atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast">Thornhill</atom>
    <atom name="NamSuffix"></atom>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">British</atom>
    <atom name="BioBirthDate">1675</atom>
    <atom name="BioBirthEarliestDate"></atom>
    <atom name="BioBirthLatestDate"></atom>
    <atom name="BioBirthPlace"></atom>
    <atom name="BioDeathDate">1734</atom>
    <atom name="BioDeathEarliestDate"></atom>
    <atom name="BioDeathLatestDate"></atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">painter</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">draftsman</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">decorative artist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">ceiling painter</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">portraitist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">court artist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">illustrator</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">designer</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">teacher</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2016-08-17</atom>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="irn">619988</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Place Holder</atom>
    <atom name="NamFullName">Jonathan Richardson the elder</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst">Jonathan</atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast">Richardson</atom>
    <atom name="NamSuffix">the elder</atom>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">British</atom>
    <atom name="BioBirthDate">1665</atom>
    <atom name="BioBirthEarliestDate">1665</atom>
    <atom name="BioBirthLatestDate">1665</atom>
    <atom name="BioBirthPlace"></atom>
    <atom name="BioDeathDate">1745</atom>
    <atom name="BioDeathEarliestDate">1745</atom>
    <atom name="BioDeathLatestDate">1745</atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">painter</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">portraitist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">writer</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">author</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">collector</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2019-01-09</atom>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="irn">737</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Place Holder</atom>
    <atom name="NamFullName">Henry Wolf</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst">Henry</atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast">Wolf</atom>
    <atom name="NamSuffix"></atom>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">American</atom>
    <atom name="BioBirthDate">1852</atom>
    <atom name="BioBirthEarliestDate">1852</atom>
    <atom name="BioBirthLatestDate">1916</atom>
    <atom name="BioBirthPlace"></atom>
    <atom name="BioDeathDate">1916</atom>
    <atom name="BioDeathEarliestDate">1852</atom>
    <atom name="BioDeathLatestDate">1916</atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2019-01-10</atom>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <atom name="irn">612140</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Person</atom>
    <atom name="NamFullName">James A. Whistler</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst">James</atom>
    <atom name="NamMiddle">Abbott McNeill</atom>
    <atom name="NamLast">Whistler</atom>
    <atom name="NamSuffix"></atom>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">American</atom>
    <atom name="BioBirthDate">1834</atom>
    <atom name="BioBirthEarliestDate">1834</atom>
    <atom name="BioBirthLatestDate">1834</atom>
    <atom name="BioBirthPlace"></atom>
    <atom name="BioDeathDate">1903</atom>
    <atom name="BioDeathEarliestDate">1903</atom>
    <atom name="BioDeathLatestDate">1903</atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">painter</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">printmaker</atom>
      </tuple>
    </table>
    <table name="GUIDs">
      <tuple>
        <atom name="AdmGUIDIsPreferred">No</atom>
        <atom name="AdmGUIDType">ULAN ID</atom>
        <atom name="AdmGUIDValue">500012432</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2022-06-08</atom>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <atom name="irn">600630</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Place Holder</atom>
    <atom name="NamFullName">Dines Carlsen</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst">Dines</atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast">Carlsen</atom>
    <atom name="NamSuffix"></atom>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">American</atom>
    <table name="Identities">
      <tuple>
        <atom name="BioCulturalInfluences">Caucasian</atom>
      </tuple>
      <tuple>
        <atom name="BioCulturalInfluences">White</atom>
      </tuple>
    </table>
    <atom name="BioBirthDate">1901</atom>
    <atom name="BioBirthEarliestDate">1901</atom>
    <atom name="BioBirthLatestDate">1901</atom>
    <atom name="BioBirthPlace">New York City, New York</atom>
    <atom name="BioDeathDate">1966</atom>
    <atom name="BioDeathEarliestDate">1966</atom>
    <atom name="BioDeathLatestDate">1966</atom>
    <atom name="BioDeathPlace">New York City, New York</atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">painter</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2022-02-24</atom>
  </tuple>

  <!-- Row 9 -->
  <tuple>
    <atom name="irn">615130</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Person</atom>
    <atom name="NamFullName">Robert Indiana</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst">Robert</atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast">Indiana</atom>
    <atom name="NamSuffix"></atom>
    <table name="OtherPersonNames">
      <tuple>
        <atom name="NamOtherNames">Robert Clark</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Bob Indiana</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Bob Clark</atom>
      </tuple>
    </table>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">American</atom>
    <atom name="BioBirthDate">1928</atom>
    <atom name="BioBirthEarliestDate">1928</atom>
    <atom name="BioBirthLatestDate">1928</atom>
    <atom name="BioBirthPlace">New Castle, Indiana</atom>
    <atom name="BioDeathDate">2018</atom>
    <atom name="BioDeathEarliestDate">2018</atom>
    <atom name="BioDeathLatestDate">2018</atom>
    <atom name="BioDeathPlace">Vinalhaven, Maine</atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">painter</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">sculptor</atom>
      </tuple>
    </table>
    <table name="GUIDs">
      <tuple>
        <atom name="AdmGUIDIsPreferred">No</atom>
        <atom name="AdmGUIDType">ULAN ID</atom>
        <atom name="AdmGUIDValue">500015478</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2022-06-08</atom>
  </tuple>

  <!-- Row 10 -->
  <tuple>
    <atom name="irn">10433</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Organisation</atom>
    <atom name="NamFullName">Lippincott, LLC</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst"></atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast"></atom>
    <atom name="NamSuffix"></atom>
    <atom name="NamSex">Unknown</atom>
    <atom name="BioNationality">American</atom>
    <atom name="BioBirthDate"></atom>
    <atom name="BioBirthEarliestDate"></atom>
    <atom name="BioBirthLatestDate"></atom>
    <atom name="BioBirthPlace"></atom>
    <atom name="BioDeathDate"></atom>
    <atom name="BioDeathEarliestDate"></atom>
    <atom name="BioDeathLatestDate"></atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation">Lippincott, LLC</atom>
    <atom name="NamOrganisationAcronym"></atom>
    <table name="OtherOrgNames">
      <tuple>
        <atom name="NamOrganisationOtherNames">Lippincott Foundry</atom>
      </tuple>
      <tuple>
        <atom name="NamOrganisationOtherNames">Lippincott's, LLC</atom>
      </tuple>
    </table>
    <atom name="IMAHisCommenced">1966</atom>
    <atom name="IMAHisBeginEarliestDate">1966</atom>
    <atom name="IMAHisBeginLatestDate">1966</atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">foundry</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2019-02-18</atom>
  </tuple>

  <!-- Row 11 -->
  <tuple>
    <atom name="irn">592</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Person</atom>
    <atom name="NamFullName">Utagawa Hiroshige</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst"></atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast">Utagawa Hiroshige 歌川広重</atom>
    <atom name="NamSuffix"></atom>
    <table name="OtherPersonNames">
      <tuple>
        <atom name="NamOtherNames">Hiroshige</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Hiroshige Utagawa</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Ando Hiroshige</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Utagawa Hir^oshige</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Andō Hiroshige  安藤広重</atom>
      </tuple>
    </table>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">Japanese</atom>
    <atom name="BioBirthDate">1797</atom>
    <atom name="BioBirthEarliestDate">1797</atom>
    <atom name="BioBirthLatestDate">1797</atom>
    <atom name="BioBirthPlace"></atom>
    <atom name="BioDeathDate">1858</atom>
    <atom name="BioDeathEarliestDate">1858</atom>
    <atom name="BioDeathLatestDate">1858</atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
    </table>
    <table name="GUIDs">
      <tuple>
        <atom name="AdmGUIDIsPreferred">No</atom>
        <atom name="AdmGUIDType">ULAN ID</atom>
        <atom name="AdmGUIDValue">500019641</atom>
      </tuple>
      <tuple>
        <atom name="AdmGUIDIsPreferred">No</atom>
        <atom name="AdmGUIDType">Wikidata QID</atom>
        <atom name="AdmGUIDValue">Q200798</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2022-06-08</atom>
  </tuple>

  <!-- Row 12 -->
  <tuple>
    <atom name="irn">606727</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Person</atom>
    <atom name="NamFullName">James C. Beckwith</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst">James</atom>
    <atom name="NamMiddle">Carroll</atom>
    <atom name="NamLast">Beckwith</atom>
    <atom name="NamSuffix"></atom>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">American</atom>
    <table name="Identities">
      <tuple>
        <atom name="BioCulturalInfluences">Caucasian</atom>
      </tuple>
      <tuple>
        <atom name="BioCulturalInfluences">White</atom>
      </tuple>
    </table>
    <atom name="BioBirthDate">1852</atom>
    <atom name="BioBirthEarliestDate">1852</atom>
    <atom name="BioBirthLatestDate">1852</atom>
    <atom name="BioBirthPlace">Hannibal, Missouri</atom>
    <atom name="BioDeathDate">1917</atom>
    <atom name="BioDeathEarliestDate">1917</atom>
    <atom name="BioDeathLatestDate">1917</atom>
    <atom name="BioDeathPlace">New York, New York</atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">painter</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2022-02-18</atom>
  </tuple>

  <!-- Row 13 -->
  <tuple>
    <atom name="irn">10661</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="NamPartyType">Person</atom>
    <atom name="NamFullName">Unknown 作者不詳</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst"></atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast">Unknown 作者不詳</atom>
    <atom name="NamSuffix"></atom>
    <atom name="NamSex">Unknown</atom>
    <atom name="BioNationality">Japanese</atom>
    <atom name="BioBirthDate"></atom>
    <atom name="BioBirthEarliestDate"></atom>
    <atom name="BioBirthLatestDate"></atom>
    <atom name="BioBirthPlace"></atom>
    <atom name="BioDeathDate"></atom>
    <atom name="BioDeathEarliestDate"></atom>
    <atom name="BioDeathLatestDate"></atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2019-01-09</atom>
  </tuple>

  <!-- Row 14 -->
  <tuple>
    <atom name="irn">11481</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="NamPartyType">Person</atom>
    <atom name="NamFullName">Halston</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst"></atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast">Halston</atom>
    <atom name="NamSuffix"></atom>
    <table name="OtherPersonNames">
      <tuple>
        <atom name="NamOtherNames">Roy Halston Frowick</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Roy Frowick</atom>
      </tuple>
    </table>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">American</atom>
    <table name="Identities">
      <tuple>
        <atom name="BioCulturalInfluences">LGBTQ+</atom>
      </tuple>
    </table>
    <atom name="BioBirthDate">1932</atom>
    <atom name="BioBirthEarliestDate">1932</atom>
    <atom name="BioBirthLatestDate">1932</atom>
    <atom name="BioBirthPlace">Des Moines, Iowa</atom>
    <atom name="BioDeathDate">1990</atom>
    <atom name="BioDeathEarliestDate">1990</atom>
    <atom name="BioDeathLatestDate">1990</atom>
    <atom name="BioDeathPlace">San Francisco, California</atom>
    <atom name="NamOrganisation"></atom>
    <atom name="NamOrganisationAcronym"></atom>
    <atom name="IMAHisCommenced"></atom>
    <atom name="IMAHisBeginEarliestDate"></atom>
    <atom name="IMAHisBeginLatestDate"></atom>
    <atom name="IMAHisCompleted"></atom>
    <atom name="IMAHisEndEarliestDate"></atom>
    <atom name="IMAHisEndLatestDate"></atom>
    <atom name="ColCollaborationName"></atom>
    <table name="Roles">
      <tuple>
        <atom name="NamRoles">fashion designer</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">milliner</atom>
      </tuple>
      <tuple>
        <atom name="NamRoles">artist</atom>
      </tuple>
    </table>
    <atom name="AdmDateModified">2021-07-29</atom>
  </tuple>

  <!-- Row 15 -->
  <tuple>
    <atom name="irn">11366</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="NamPartyType">Person</atom>
    <atom name="NamFullName">Utagawa Kunisada 歌川国貞</atom>
    <atom name="NamTitle"></atom>
    <atom name="NamFirst"></atom>
    <atom name="NamMiddle"></atom>
    <atom name="NamLast">Utagawa Kunisada 歌川国貞</atom>
    <atom name="NamSuffix"></atom>
    <table name="OtherPersonNames">
      <tuple>
        <atom name="NamOtherNames">Utagawa Kunisada</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Sumida Shozo</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Tsunda Shozo</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Shozo</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Gototei</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Ichiyosai</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Gepparo</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Kinraisha</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Kochoro</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Toyokuni III</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Sanjin</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Hanabusa Ittei</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Fucho</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Kio</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Bukiyo Matahei</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Toyokuni 豊国</atom>
      </tuple>
      <tuple>
        <atom name="NamOtherNames">Toyokuni</atom>
      </tuple>
    </table>
    <atom name="NamSex">Male</atom>
    <atom name="BioNationality">Japanese</atom>
    <atom name="BioBirthDate">1786</atom>
    <atom name="BioBirthEarliestDate">1786</atom>
    <atom name="BioBirthLatestDate">1786</atom>
    <atom name="BioBirthPlace"></atom>
    <atom name="BioDeathDate">1864</atom>
    <atom name="BioDeathEarliestDate">1864</atom>
    <atom name="BioDeathLatestDate">1864</atom>
    <atom name="BioDeathPlace"></atom>
    <atom name="NamOrganisation"></atom>